In [1]:
import numpy as np
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold

C:\Users\Lenovo\anaconda3\envs\monsoon\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index

In [2]:
df = pd.read_csv('preprocessed_data.csv')
df.head()

,Unique_ID,C1,C2,C3,C4,C5,C6,C7,C8,N1,...,N19,N20,N21,N22,N23,N24,N33,N34,N35,Dependent_Variable
0,Candidate_48134,1,4,2,66,2,False,1,True,11.05,...,25856.0,17.0,0.88,1.0,40.0,10833.333330,160.0,262.10,17.0,0
1,Candidate_51717,1,0,19,2,0,False,0,True,29.00,...,11041.3,21.8,0.90,0.9,20.0,6250.000000,24.0,50.29,18.0,1
2,Candidate_26401,1,1,16,47,1,False,4,True,17.99,...,1006.0,6.0,1.00,0.0,26.0,2413.666667,70.0,126.52,27.0,0
3,Candidate_34872,1,1,13,1,1,True,6,True,27.50,...,3398.0,31.0,0.96,0.0,44.0,7666.666667,100.0,205.47,21.0,0
4,Candidate_29660,1,0,30,13,2,False,2,True,13.50,...,4110.0,11.0,0.90,2.0,48.0,4250.000000,150.0,254.51,13.0,0

In [3]:
X = df.drop(['Unique_ID', 'Dependent_Variable'], axis=1).copy()
y = df['Dependent_Variable']

In [4]:
model = XGBClassifier(verbose=10, n_jobs=-1)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
scores = cross_val_score(model, X, y, scoring='roc_auc', cv=cv, n_jobs=-1)
print('Mean ROC AUC: %.4f' % np.mean(scores))

Mean ROC AUC: 0.7593